apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: speckleserver-git-tagging
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: speckleserver-git-tagging
  chart:
    git: git@github.com:RoyalHaskoningDHV/speckle-infra
    path: helm/charts/speckleserver
    ref: v1.0.1
  values:
    image:
      repository: rhdhvcontainerregistry.azurecr.io/speckleserver
    customer: gittags
    imagePullSecrets: 
      - name: rhdhv-acr-login
    