---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: andy-test
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: andy-test
  chart:
    repository: https://rhdhvcontainerregistry.azurecr.io/helm/v1/repo/
    name: speckleserver
    version: 1.0.11
  values:
    image:
      repository: rhdhvcontainerregistry.azurecr.io/speckleserver
      tag: 1.0.11
      customer: jellybean
    imagePullSecrets:
    - name: rhdhv-acr-login
