apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: speckleserver-git
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: speckleserver-git
  chart:
    git: git@github.com:RoyalHaskoningDHV/speckle-infra
    path: helm/charts/speckleserver
    ref: DEVOPS-234-implement-ci-cd-for-helm-charts
  values:
    image:
      repository: rhdhvcontainerregistry.azurecr.io/speckleserver
    customer: andy-test
    imagePullSecrets: 
      - name: rhdhv-acr-login
    