---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: speckleserver-git
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: speckleserver-git
  chart:
    git: git@github.com:RoyalHaskoningDHV/speckle-infra
    path: helm/charts/speckleserver
    ref: staging
  values:
    image:
      repository: rhdhvcontainerregistry.azurecr.io/speckleserver
      tag: 1.0.13
    customer: andy-test
    imagePullSecrets:
    - name: rhdhv-acr-login
